name: Terraform CI

on:
  push:
    branches:
      - main
      - test/ci-check
  pull_request:

jobs:
  terraform-ci:
    name: Terraform Format, Validate, Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="../dev/terraform.tfvars"
        working-directory: environments/dev
